services:
  oca-api:
    image: nachocode/oca:api-alpha.1
    ports:
      - "5000:5000" # Map the host port to the container port
    environment:
      - OCA_API_HOST=${OCAA_API_HOST:-0.0.0.0}   # Host environment variable
      - OCA_API_PORT=${OCA_API_PORT:-5000}   # Port environment variable
      - ACCESS_TOKEN_EXPIRE_MINUTES=30  # Token expiration time (in minutes)
    command: >
      uvicorn ocaapi.server:app 
      --host ${OCA_API_HOST:-0.0.0.0} 
      --port ${OCA_API_PORT:-5000} 
      --log-level debug
    networks:
     - oca

 
networks:
  oca:

